/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Service, SupplementProduct, Testimonial } from "./types";

// Images generated by the prompt
export const IMAGES = {
  dnaBg: "/src/assets/images/dna_particle_bg_1780597239950.png",
  vitalityBottle: "/src/assets/images/vitality_supplement_1780597257282.png",
  drArunMaji: "/src/assets/images/dr_arun_maji_1780597274459.png",
};

export const CLINIC_INFO = {
  name: "Sydney Doctor Biohealth Pvt Ltd",
  phone: "62899 21810",
  phoneFormatted: "+91 62899 21810",
  email: "sportsdoctoraustralia@gmail.com",
  cin: "U21009WB2025PTC285535",
  clinicAddress: {
    line1: "Building 7, Plot 3",
    line2: "3088 Rajdanga Main Road, Kasba",
    city: "Kolkata",
    pincode: "700107",
    full: "Building 7, Plot 3, 3088 Rajdanga Main Road, Kasba, Kolkata 700107"
  },
  officeAddress: {
    line1: "Fl 402, 3rd Floor",
    line2: "7B Seven Tanks Lane, Ghughudanga",
    city: "Kolkata",
    pincode: "700030",
    full: "Fl 402, 3rd Floor, 7B Seven Tanks Lane, Ghughudanga, Kolkata 700030"
  },
  mapsCoords: {
    lat: 22.5126,
    lng: 88.3969,
  }
};

export const SERVICES_DATA: Service[] = [
  {
    id: "weight-management",
    shorthand: "Weight Management",
    title: "Medical Weight Management",
    subtitle: "Address metabolic and dynamic hormonal blockages.",
    body: "Weight is not simply a lifestyle issue. It is a clinical one. Hormonal imbalances, metabolic disorders, nutritional deficiencies, and systemic inflammation all play a role in why weight resists your efforts. We assess the full picture and build a medical protocol designed for your physiology — not a generic diet plan.",
    assessments: [
      "Metabolic rate & thyroid panel structure",
      "Insulin sensitivity & glycemic curves",
      "Cortisol cycles & stress response indicators",
      "Gut inflammatory biomarkers",
      "Active micronutrient and co-enzyme deficiencies"
    ],
    ctaText: "Book Metabolic Assessment"
  },
  {
    id: "sexual-performance",
    shorthand: "Sexual Performance",
    title: "Sexual Performance & Hormonal Health",
    subtitle: "Science-based testosterone assessment and systemic vitality.",
    body: "Sexual health is one of the most underdiagnosed and undertreated areas of medicine in India. Low libido, erectile dysfunction, hormonal imbalances, and reduced vitality are clinical conditions — not personal failures. We provide confidential, evidence-based consultation in a safe, science-first, and highly professional medical clinic.",
    assessments: [
      "Testosterone and free androgen profiles",
      "Thyroid and pituitary regulatory function",
      "Endothelial vascular function markers",
      "Psychosomatic fatigue indices",
      "Essential trace element balances"
    ],
    ctaText: "Request Confidential Consultation"
  },
  {
    id: "fatigue-management",
    shorthand: "Fatigue Management",
    title: "Fatigue & Energy Optimisation",
    subtitle: "Locate and correct physical exhaustion at the trace level.",
    body: "Persistent fatigue is not something you should accept as normal. Chronic tiredness, brain fog, low motivation, and poor recovery are your body's signals that something is clinically wrong. We investigate the root causes — not just mask the symptoms.",
    assessments: [
      "Iron indices & active ferritin storage",
      "Serum Vitamin B12 & biological folate profiles",
      "Vitamin D3 & calcium regulation markers",
      "Extended thyroid & adrenal function charts",
      "Mitochondrial nutrient assimilation parameters"
    ],
    ctaText: "Resolve Chronic Fatigue"
  },
  {
    id: "physical-performance",
    shorthand: "Physical Performance",
    title: "Physical Performance Optimisation",
    subtitle: "Unlock peak biological efficiency for serious longevity.",
    body: "Whether you are an athlete, a fitness enthusiast, or simply someone who wants to feel strong and capable, we design clinical performance protocols that help your body function at its ceiling — not its floor.",
    assessments: [
      "Lean muscle mass and cellular body composition",
      "Pro-inflammatory cytokine profiles",
      "Exercise recovery speed & systemic biomarkers",
      "Optimal physiological nutrient mapping",
      "Hormonal baseline optimization zones"
    ],
    ctaText: "Optimize Performance"
  },
  {
    id: "sports-injury",
    shorthand: "Sports Injury",
    title: "Sports Injury Assessment & Management",
    subtitle: "Rapid repair and biomechanical biohealth healing protocols.",
    body: "Injuries are not just physical setbacks — they are performance threats. Our sports injury management approach goes beyond pain relief to address the biomechanical, nutritional, and recovery factors that determine how fast and how completely you return to peak performance.",
    assessments: [
      "Structural injury indexing & tissue grading",
      "Systemic healing & cell regeneration kinetics",
      "Local movement and loading patterns",
      "Hyper-targeted nutritional repair support",
      "Accelerated recovery tracking checkpoints"
    ],
    ctaText: "Schedule Injury Assessment"
  }
];

export const SUPPLEMENT_PRODUCTS: SupplementProduct[] = [
  {
    id: "vitality-support",
    title: "Men's & Women's Vitality Support",
    category: "Vitality Support",
    tagline: "Clinical Hormonal Foundations",
    description: "Designed for men and women experiencing a decline in energy, libido, and overall vitality. Our vitality formulas target the biological foundations of daily stamina and hormonal harmony.",
    science: "Formulated with clinical-grade, bioavailable trace elements and adaptogens known to support normal endocrine pathways.",
    benefits: [
      "Supports stable free testosterone & hormonal expression",
      "Enhances metabolic stamina and vitality reserves",
      "Optimized bio-absorption profiles"
    ],
    image: IMAGES.vitalityBottle
  },
  {
    id: "performance-support",
    title: "Extreme Performance Support",
    category: "Performance Support",
    tagline: "Sustained Power & Rapid Recovery",
    description: "For active people who train, compete, or demand absolute physiological outputs. Our performance support range is built around what the science actually shows — not what the fitness industry labels.",
    science: "Contains science-backed energy precursors and co-factors to optimize mitochondrial ATP synthases inside active cells.",
    benefits: [
      "Accelerated cell recovery periods",
      "Mitigates exercise-induced oxygen stress",
      "Provides sustained cellular stamina without spikes"
    ],
    image: IMAGES.vitalityBottle // using high premium bottle mockup
  },
  {
    id: "heart-brain-support",
    title: "Premium Heart & Brain Support",
    category: "Heart & Brain Support",
    tagline: "Cognitive Fortitude & Endothelial Integrity",
    description: "Cardiovascular and cognitive health are the long game. Our formulations support arterial health, blood pressure regulation, and cognitive focus with evidence-validated compounds at clinically meaningful doses.",
    science: "Includes standardized marine omega essential esters and powerful neuro-protective co-enzymes.",
    benefits: [
      "Optimizes vascular compliance and blood velocity",
      "Aids neurotransmitter health and mitigates brain fog",
      "Promotes structural cardiorespiratory cell defense"
    ],
    image: IMAGES.vitalityBottle
  },
  {
    id: "clinical-multivitamin",
    title: "Advanced Clinical Multivitamin",
    category: "Clinical Multivitamin",
    tagline: "Dosed for True Biological Absorption",
    description: "Not all multivitamins are created equal. Ours are dosed at levels that actually make a clinical difference, with bioavailable forms of each nutrient chosen for real-world absorption — not label optics.",
    science: "100% active organic trace minerals, complete with activated methyl-cobalamin (B12) and bioactive D3 structures.",
    benefits: [
      "Addresses general micronutrient starvation zones",
      "Enhances cellular immune defense indices",
      "Guarantees maximum gastrointestinal absorption"
    ],
    image: IMAGES.vitalityBottle
  }
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: "priyanka-kolkata",
    name: "Priyanka",
    rating: 5,
    category: "Fatigue & Energy",
    pullQuote: "I thought I was simply unfit. Tests revealed low iron, B12, and D. Once resolved with the right clinical protocol, everything changed.",
    expandedQuote: "I thought I was simply unfit. Five minutes into any training session, I was already breathless and exhausted. I had accepted it as my normal. Through Sydney Doctor's health education and diagnostic approach, I learned to consider what was happening inside my body — not just on the surface. Tests revealed low iron, low Vitamin B12, and low Vitamin D. Once those deficiencies were identified and corrected with the right clinical protocol, everything changed. I now train for forty minutes with complete ease. Don't train blindly. Train guided by science.",
    location: "Kolkata",
    resultSummary: "Resolved chronic fatigue, corrected three major deficiencies, returned to sustained exercise performance.",
    keyLesson: "Always investigate root causes before attributing poor athletic performance to effort."
  },
  {
    id: "moak-engineering",
    name: "MOAK Engineering & Consultancy Pvt. Ltd",
    rating: 5,
    category: "Corporate Wellness / International Standards",
    pullQuote: "A wonderful start to accessing National & International standard healthcare.",
    expandedQuote: "As a corporate organisation, we hold our standards high — and Sydney Doctor Biohealth met them without compromise. From the very first interaction, it was clear that this is not an ordinary clinic. The access to national and international-grade facilities, combined with Dr. Maji's structured and science-led approach, gave us complete confidence. This is the kind of performance health partnership that serious organisations and individuals deserve. A wonderful start, and we look forward to a long association.",
    location: "Kolkata",
    resultSummary: "Delivered international standard diagnostic and executive protocols for peak corporate capability."
  },
  {
    id: "paulomi-das",
    name: "Paulomi Das",
    rating: 5,
    category: "General Practice Care",
    pullQuote: "The service at Sydney Doctor is exceptional — professional, thorough, and genuinely caring.",
    expandedQuote: "I came to Sydney Doctor Biohealth not entirely sure what to expect. What I received was a level of service that I had not experienced at any clinic before in Kolkata. The entire process — from booking to consultation — was seamless and professional. Dr. Maji took the time to understand my concerns fully before offering any guidance, which made all the difference. This is what good medicine should feel like. I would recommend Sydney Doctor to anyone who is serious about their health.",
    location: "Kolkata",
    resultSummary: "Highly professional service layout; comprehensive patient inquiry response."
  },
  {
    id: "riju-chakraborty",
    name: "Riju Chakraborty",
    rating: 5,
    category: "Structured Medicine",
    pullQuote: "A genuinely good experience — the kind of care that actually makes a difference.",
    expandedQuote: "Sydney Doctor Biohealth gave me the kind of clinical experience I had been searching for in Kolkata for a long time. The consultation was structured, the doctor was attentive, and the recommendations were grounded in actual science — not vague lifestyle advice. I left with a clear plan and, more importantly, a real understanding of what my body needed. The overall experience was outstanding, and I will definitely be returning for follow-ups. This is performance medicine done right.",
    location: "Kolkata",
    resultSummary: "Formulated a structural bio-strategy for sustainable long-term recovery."
  },
  {
    id: "rahul-shaw",
    name: "Rahul Shaw",
    rating: 5,
    category: "Weight Management",
    pullQuote: "Finally — a proper, medically-guided weight loss service in Kolkata.",
    expandedQuote: "I have tried multiple weight loss programmes over the years — gym trainers, dieticians, online plans — and none of them gave me lasting results. The reason, as I discovered at Sydney Doctor, is that my weight issue had a clinical root cause that was never properly investigated. Dr. Maji assessed my metabolic profile, identified the underlying issue, and built a structured medical protocol specifically for me. It is a completely different experience from anything else available in Kolkata. For the first time, I feel like I am actually making real, sustainable progress. If you are serious about weight management, this is where you need to be.",
    location: "Kolkata",
    resultSummary: "Identified hormonal blocking points, successfully reducing metabolic weight blockages."
  },
  {
    id: "hassan-gain",
    name: "Hassan Gain",
    rating: 5,
    category: "International Standards",
    pullQuote: "International-level healthcare, right here in Kolkata.",
    expandedQuote: "What strikes you immediately about Sydney Doctor Biohealth is the standard of care. It is not what you typically find in a local clinic — it is the kind of structured, rigorous, evidence-based medicine that you associate with international healthcare systems. Dr. Maji brings his two decades of experience in Sydney, Australia directly into the consultation room in Kolkata. The clinical assessment, the communication, the follow-up — everything is conducted at a global level. I am genuinely proud that Kolkata now has a facility of this calibre. For anyone who refuses to settle for ordinary healthcare, Sydney Doctor is the answer.",
    location: "Kolkata",
    resultSummary: "Acquired Australian primary care precision and robust post-consult medical support."
  },
  {
    id: "soumen-samanta",
    name: "Soumen Samanta",
    rating: 5,
    category: "Facilities & Operations",
    pullQuote: "Well-equipped, professional, and genuinely impressive — this is a clinic that sets a new standard.",
    expandedQuote: "I visited Sydney Doctor Biohealth with some scepticism — I had been to many clinics that promised a lot and delivered very little. Sydney Doctor was different from the moment I walked in. The facilities are modern and well-equipped, the environment is professional and calm, and the service from start to finish exceeded my expectations. Dr. Maji is thorough, knowledgeable, and deeply invested in his patients' outcomes. I came away genuinely impressed — not just by the consultation, but by the entire experience. This is what a premium health clinic should look and feel like. Highly recommended.",
    location: "Kolkata",
    resultSummary: "Smooth operational transition, access to superior on-site diagnostics."
  },
  {
    id: "ram-kr-yadav",
    name: "Ram Kr Yadav",
    rating: 5,
    category: "Consultation Standards",
    pullQuote: "Five stars — a doctor and clinic that truly delivers.",
    expandedQuote: "My experience at Sydney Doctor Biohealth deserves nothing less than five stars. The professionalism, the clinical knowledge, and the genuine concern for patient wellbeing set this practice apart from anything I have encountered in Kolkata. Dr. Maji's approach is methodical — he does not rush, he does not guess, and he does not offer generic solutions. He listens, assesses, and acts on real clinical findings. For anyone looking for a doctor who treats you as an individual rather than a number, I give Sydney Doctor my highest recommendation.",
    location: "Kolkata",
    resultSummary: "Formulated custom cellular nutrition charts with meticulous diagnostics."
  },
  {
    id: "sachin-dev-baruri",
    name: "Sachin Dev Baruri",
    rating: 5,
    category: "Trust & Clinical Integrity",
    pullQuote: "A doctor you can trust completely — rare and invaluable.",
    expandedQuote: "Finding a doctor you can truly trust in today's healthcare landscape is rare. At Sydney Doctor Biohealth, that trust is earned immediately. Dr. Arun Maji brings an extraordinary depth of clinical experience and a rigorous scientific mindset to every consultation. There is no guesswork, no unnecessary prescriptions, and no vague advice — only structured, evidence-based clinical care. The level of integrity here is exceptional. I left my appointment with absolute clarity on my health status and a clear, science-backed path forward. Sydney Doctor has set a new benchmark for what a healthcare consultation in Kolkata should be.",
    location: "Kolkata",
    resultSummary: "Absolute clarity of treatment protocol; no pushy pharmaceutical biases."
  },
  {
    id: "bulti-maji",
    name: "Bulti Maji",
    rating: 5,
    category: "Hormonal & Vitality Recovery",
    pullQuote: "Sydney Doctor changed how I think about my health — and changed my results.",
    expandedQuote: "I came to Sydney Doctor Biohealth at a point where I had been struggling with low energy and persistent fatigue for over a year. Nothing I tried had made a meaningful difference. Within a single comprehensive consultation, Dr. Maji had identified clinical factors that had gone completely unnoticed by other practitioners. The approach here is unlike anything else — it is not about symptom management, it is about root cause resolution. Following Dr. Maji's protocol, my energy levels have improved significantly and I finally feel like myself again. Sydney Doctor does not just treat you — they transform how you understand and manage your own health.",
    location: "Kolkata",
    resultSummary: "Corrected core hormonal pathways, fully restoring high-performance vigor."
  },
  {
    id: "rupa-sarkar",
    name: "Rupa Sarkar",
    rating: 5,
    category: "Women's Wellness & Integrity",
    pullQuote: "A clinic that understands women's health with the seriousness it deserves.",
    expandedQuote: "As a woman, I have often felt that my health concerns were either minimised or addressed with generic solutions. Sydney Doctor Biohealth was a completely different experience. Dr. Maji took my concerns seriously from the very first moment, assessed my health comprehensively, and provided a personalised clinical protocol that addressed my specific needs. The focus on vitality, hormonal health, and overall performance as a woman — not just a patient — made me feel genuinely seen and cared for. The facilities are outstanding, the service is immaculate, and the results have been real. I am deeply grateful to have found this clinic in Kolkata.",
    location: "Kolkata",
    resultSummary: "Gained custom targeted female vitality schedules with continuous care."
  }
];

export const TRUST_POINTS = [
  {
    icon: "Activity",
    title: "Doctor-Led Care",
    desc: "Every clinical decision and supplement recipe is crafted directly by Dr. Arun Maji."
  },
  {
    icon: "ShieldAlert",
    title: "Science-Driven Protocols",
    desc: "Every protocol is grounded strictly in peer-reviewed biomedical research and evidence."
  },
  {
    icon: "ShieldCheck",
    title: "Safety-First Environment",
    desc: "Clinical regulations and safety frameworks benchmarked at international levels."
  },
  {
    icon: "FileSpreadsheet",
    title: "Evidence-Led Compounds",
    desc: "Clinical doses, organic bioavailability, no synthetic filler metrics."
  },
  {
    icon: "TrendingUp",
    title: "Measurable Biomarkers",
    desc: "We track bloodwork and body statistics. If we cannot measure it, we do not claim it."
  },
  {
    icon: "Users",
    title: "Limited-Capacity Practice",
    desc: "Fewer slots, rigorous custom clinical attention. You are a human, not a volume statistic."
  },
  {
    icon: "Award",
    title: "Uncompromising Integrity",
    desc: "No paid pharmaceutical kickbacks. Absolute commitment to clinical honesty."
  },
  {
    icon: "Globe",
    title: "International Standards",
    desc: "Benchmarked directly under high-end Australian RACGP and longevity guidelines."
  }
];

export const TIMELINE_EVENTS = [
  {
    year: "2000 - 2005",
    title: "Military Medical Service",
    desc: "Served as an honored medical officer in rigorous Indian & Australian defense contexts, cultivating flawless medical discipline and deep physiological mastery."
  },
  {
    year: "2005 - 2024",
    title: "Sydney, Australia Clinical Era",
    desc: "Led complex general practice, metabolic performance, and longevity assessments in Sydney. Honed evidence-led performance medicine under premier clinical guidelines."
  },
  {
    year: "2020 - 2024",
    title: "RACGP Specialty Trainer",
    desc: "Appointed as a credentialed general medicine trainer in Queensland, Australia, mentoring physicians in state-of-the-art diagnostic protocols."
  },
  {
    year: "2022 - Present",
    title: "Published Clinical Author",
    desc: "Authored multiple referenced clinical guides focusing on nutritional therapy, performance, and male/female hormone integration benchmarks."
  },
  {
    year: "2025",
    title: "Sydney Doctor Biohealth Kolkata",
    desc: "Founded the premier Kasba clinic with a corporate mission to anchor Australia's highest longevity standards right inside India."
  }
];

export const PERFORMANCE_JOURNEY = [
  {
    step: "01",
    name: "Assessment",
    title: "Comprehensive Clinical History",
    desc: "We analyze your precise baseline including symptoms, diet parameters, physical records, and custom diagnostic testing metrics."
  },
  {
    step: "02",
    name: "Diagnosis",
    title: "Root Cause Discovery",
    desc: "We identify the exact metabolic, clinical, or hormonal blockages that drag down your physical or mental capability."
  },
  {
    step: "03",
    name: "Protocol",
    title: "Custom Cellular Roadmap",
    desc: "Dr. Maji prescribes a focused protocol combining medical directives, dietary adjustments, and bio-available supplementation."
  },
  {
    step: "04",
    name: "Monitoring",
    title: "Continuous Metric Audits",
    desc: "We routinely monitor your biomarkers, adjusting dosages and clinical plans based on actual biological feedback."
  },
  {
    step: "05",
    name: "Optimisation",
    title: "Sustained Peak Vitality",
    desc: "We transition your baseline to an elevated, self-sustaining high-performance range that protects you against future decline."
  }
];

export const FAQS = [
  {
    q: "What is Performance Medicine?",
    a: "Unlike traditional medicine which focuses strictly on reactive sickness care, Performance Medicine optimizes your metabolic, physical, and hormonal parameters to function at peak health, stamina, and longevity ceilings."
  },
  {
    q: "How are Sydney Doctor supplements designed differently?",
    a: "Our supplements are formulated by Dr. Arun Maji based on clinical evidence, using active organic forms for maximum gastrointestinal absorption and at meaningful clinical doses rather than tiny quantities used for marketing claims."
  },
  {
    q: "Where is the clinic located?",
    a: "Our diagnostic head office clinic is situated at Building 7, Plot 3, 3088 Rajdanga Main Road, Kasba, Kolkata 700107. You can contact us at 62899 21810 for appointments."
  },
  {
    q: "Are video assessments or virtual calls available?",
    a: "We accommodate both on-site clinical evaluations in Kolkata and robust diagnostic telemedicine consultations for high-performing clients outside West Bengal."
  }
];
